server:
  port: 0
spring:
  docker:
    compose:
      file: service-product-compose.yaml
  application:
    name: service-product
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    hostname: localhost